version: '3.4'

services:
  catalogDb:
    container_name: catalogDb
    networks:
      - eshoppingNet
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketDb:
    container_name: basketDb
    networks:
      - eshoppingNet
    ports:
      - "6379:6379"
  
  discountDb:
    container_name: discountDb
    networks:
      - eshoppingNet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres@123
      - POSTGRES_DB=DiscountDb
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  catalogApi:
    container_name: catalogApi
    networks:
      - eshoppingNet
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__ProductsCollection=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
    depends_on:
      - catalogDb
    ports:
      - "7000:80"

  basketApi:
    container_name: basketApi
    networks:
      - eshoppingNet
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379"
    depends_on:
      - basketDb
    ports:
      - "7001:80"

  discountApi:
    container_name: discountApi
    networks:
      - eshoppingNet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=SERVER=discountDb;PORT=5432;DATABASE=DiscountDb;User ID=postgres; Password=postgres@123;"      
    depends_on:
      - discountDb
    ports:
      - "7002:80"


  pgadmin:
    container_name: pgadmin
    networks:
      - eshoppingNet
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@eShopping.net
      - PGADMIN_DEFAULT_PASSWORD=pgadmin@123
    restart: unless-stopped
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin


  portainer:
    container_name: portainer
    networks:
      - eshoppingNet
    restart: unless-stopped
    ports:
      - "8080:8000"
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  