version: '3.4'
networks:
  eshoppingNet:
    driver: bridge

services:
  catalogDb:
    image: mongo

  basketDb:
    image: redis:alpine

  discountDb:
    image: postgres:15.3


  catalogApi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basketApi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discountApi:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile


  portainer:
    image: portainer/portainer-ce

  pgadmin:
    image: dpage/pgadmin4
      

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
